- name: Disable swap and remove entry from /etc/fstab
  command: swapoff -a

- name: remove entry from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#\s]+\s+){2}swap\s+'
    replace: '# \g<0>'

- name: Ensure overlay and br_netfilter modules are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Configure modules to load at boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Configure required sysctl to persist across system reboots
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Apply sysctl parameters without rebooting
  command: sysctl --system