---
- name: Get join command from main control plane
  shell: kubeadm token create --print-join-command
  register: join_command
  when: "'k8s_master' in group_names"

- name: Check if node has been initialized
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf
  when: "'k8s_worker' in group_names"

- name: Join worker node to the cluster
  shell: "{{ hostvars[groups['k8s_master'][0]]['join_command']['stdout'] }}"
  when: 
    - "'k8s_worker' in group_names"
    - not kubelet_conf.stat.exists